######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 5 19:28:09 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myclass.h
SOURCES += main.cpp myclass.cpp
QT += network
