/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_B_H_RPCGEN
#define _PART_B_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct paths {
	char path_1[200];
	char path_2[200];
};
typedef struct paths paths;

#define PARTB_PROG 0x12345678
#define PARTB_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define part_b 1
extern  int * part_b_1(paths *, CLIENT *);
extern  int * part_b_1_svc(paths *, struct svc_req *);
extern int partb_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define part_b 1
extern  int * part_b_1();
extern  int * part_b_1_svc();
extern int partb_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_paths (XDR *, paths*);

#else /* K&R C */
extern bool_t xdr_paths ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_B_H_RPCGEN */
